services:
    portfoliov3-front:
        user: "${UID:-1000}:${GID:-1000}"
        build:
            context: .
            dockerfile: .docker/Dockerfile
            target: ${APP_ENV:-dev}
        container_name: portfoliov3-front
        environment:
            APP_ENV: ${APP_ENV:-dev}
            HOST: 0.0.0.0
            PORT: 3000
            DOMAIN: ${DOMAIN}
        env_file:
          - .env  # charge les variables Nuxt depuis .env
        volumes:
            - "./:/var/www/html"
            - "./traefik/config/traefik.${APP_ENV:-dev}.yml:/etc/traefik/traefik.yml:ro"
            - "front_node_modules:/var/www/html/node_modules"
        networks:
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.portfoliov3-front.rule=Host(`${DOMAIN:-localhost}`)"
            - "traefik.http.services.portfoliov3-front.loadbalancer.server.port=3000"
        extra_hosts:
            - "portfoliov3.dev.local:127.0.0.1"
volumes:
    front_node_modules:
networks:
    web:
        external: true
