apiVersion: v1
kind: ConfigMap
metadata:
    name: nuxt-front-config
    namespace: portfoliov3-front
data:
    NODE_ENV: "production"
    NUXT_PUBLIC_SITE_URL: "https://jonathanlore.fr"
    NUXT_PUBLIC_API_BASE_URL: "https://api.jonathanlore.fr"
    NUXT_PUBLIC_MATOMO_URL: "https://matomo.jonathanlore.fr"
    NUXT_PUBLIC_MATOMO_SITE_ID: "1"
